[package]
name = "learn_actix"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
json = "0.12.4"
serde = {version = "1.0" , features = ["derive"]}